from abc import ABC, abstractmethod
from typing import List

class IEmbeddingPort(ABC):
    """Port contract for generating text embeddings using an AI model."""

    @abstractmethod
    async def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generates embedding vectors for a list of texts in batch.
        Returns a list of vectors, where each vector is a list of floats.
        """
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Returns the dimension of the embedding vectors generated by the model."""
        pass

    @property
    def requires_pacing(self) -> bool:
        """Returns whether the model requires rate limit pacing between batches."""
        return True
