import asyncio
import httpx
from typing import List
from loguru import logger
import math

from app.core.config import settings
from app.core.exceptions import EmbeddingException
from app.application.interfaces.embedding_port import IEmbeddingPort

class HuggingFaceEmbeddingAdapter(IEmbeddingPort):
    """Adapter for generating text embeddings using Hugging Face (via Inference API or local Transformers model)."""

    def __init__(self):
        # Read settings, default to BAAI/bge-small-en-v1.5 which matches the project's 384 dimensions
        self.model_name = getattr(settings, "HF_EMBEDDING_MODEL", None) or "BAAI/bge-small-en-v1.5"
        self.api_token = getattr(settings, "HF_API_TOKEN", None)
        self.use_local = getattr(settings, "HF_USE_LOCAL", False)
        
        # Local model instances (lazy-loaded to save startup time and memory if using the API)
        self._local_tokenizer = None
        self._local_model = None

        # Determine the execution path
        if self.use_local:
            logger.info(f"HuggingFace adapter initialized to use LOCAL model: {self.model_name}")
        elif not self.api_token or self.api_token == "huggingface-token" or self.api_token == "":
            logger.warning(
                "HF_API_TOKEN is not configured or empty. HuggingFace adapter will fall back to LOCAL model execution."
            )
            self.use_local = True
        else:
            logger.info(f"HuggingFace adapter initialized using INFERENCE API for model: {self.model_name}")

    @property
    def dimension(self) -> int:
        """Returns the dimension of the embedding vectors generated by the model."""
        # BAAI/bge-small-en-v1.5 returns 384-dimensional vectors
        # sentence-transformers/all-MiniLM-L6-v2 returns 384-dimensional vectors
        # BAAI/bge-large-en-v1.5 returns 1024-dimensional vectors
        if "bge-large" in self.model_name.lower():
            return 1024
        elif "all-minilm" in self.model_name.lower() or "bge-small" in self.model_name.lower():
            return 384
        return 384  # Default fallback dimension

    @property
    def requires_pacing(self) -> bool:
        """Returns whether the model requires rate limit pacing between batches."""
        # API requires pacing to handle serverless rate limits; local model does not
        return not self.use_local

    async def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Generates embedding vectors for a list of texts in batch."""
        if not texts:
            return []

        # If forced local, use local path
        if self.use_local:
            return await self._generate_embeddings_local(texts)

        # Otherwise, attempt API with a local fallback on failure (only if HF_USE_LOCAL is True)
        try:
            return await self._generate_embeddings_api(texts)
        except Exception as e:
            if not getattr(settings, "HF_USE_LOCAL", False):
                logger.error(f"Hugging Face Inference API failed: {str(e)}. Local fallback is disabled (HF_USE_LOCAL=False) to prevent OOM crash on Render.")
                raise EmbeddingException(f"Hugging Face Inference API failed after all retries: {str(e)}")
            
            logger.warning(f"Hugging Face Inference API failed: {str(e)}. Switching permanently to local fallback model.")
            self.use_local = True
            return await self._generate_embeddings_local(texts)

    async def _generate_embeddings_api(self, texts: List[str]) -> List[List[float]]:
        headers = {
            "Authorization": f"Bearer {self.api_token}",
            "Content-Type": "application/json",
            "x-wait-for-model": "true"
        }
        
        url = f"https://api-inference.huggingface.co/pipeline/feature-extraction/{self.model_name}"
        
        # BGE models perform best with queries prefixed with an instruction.
        # Check if len(texts) == 1 to determine if the call is for a RAG retrieval query.
        processed_texts = []
        is_bge = "bge" in self.model_name.lower()
        for text in texts:
            if is_bge and len(texts) == 1 and not text.startswith("Represent this sentence"):
                processed_texts.append(f"Represent this sentence for searching relevant passages: {text}")
            else:
                processed_texts.append(text)

        logger.info(f"Generating Hugging Face API embeddings for {len(texts)} texts using model {self.model_name}...")
        
        max_retries = 3
        backoff = 1.0
        for attempt in range(1, max_retries + 1):
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    response = await client.post(
                        url,
                        headers=headers,
                        json={"inputs": processed_texts}
                    )
                    
                    if response.status_code != 200:
                        raise EmbeddingException(
                            f"Hugging Face API returned status {response.status_code}: {response.text}"
                        )
                        
                    result = response.json()
                    
                    # Handle API errors returned inside the response payload
                    if isinstance(result, dict) and "error" in result:
                        raise EmbeddingException(f"Hugging Face API error: {result['error']}")
                        
                    # Perform pooling on the API response (which may return 3D token embeddings)
                    pooled_embeddings = self._pool_api_response(result)
                    
                    # Normalize embeddings for cosine similarity
                    normalized_embeddings = [self._normalize_vector(v) for v in pooled_embeddings]
                    return normalized_embeddings
            except Exception as e:
                logger.warning(f"Hugging Face API call attempt {attempt}/{max_retries} failed: {str(e)}")
                if attempt == max_retries:
                    raise
                await asyncio.sleep(backoff)
                backoff *= 2.0

    def _pool_api_response(self, api_response) -> List[List[float]]:
        if not api_response:
            return []
            
        # If the response is already 2D (list of lists of floats), return it directly
        if isinstance(api_response[0], list) and not isinstance(api_response[0][0], list):
            return api_response
            
        # If it is 3D (list of lists of lists of floats), pool it
        pooled = []
        is_bge = "bge" in self.model_name.lower()
        pooling_method = "cls" if is_bge else "mean"
        
        for text_embeddings in api_response:
            if not text_embeddings:
                pooled.append([])
                continue
            if pooling_method == "cls":
                # Take CLS token (first token embedding)
                pooled.append(text_embeddings[0])
            else:
                # Mean pooling
                seq_len = len(text_embeddings)
                emb_dim = len(text_embeddings[0])
                mean_emb = [0.0] * emb_dim
                for token_emb in text_embeddings:
                    for d in range(emb_dim):
                        mean_emb[d] += token_emb[d]
                for d in range(emb_dim):
                    mean_emb[d] /= seq_len
                pooled.append(mean_emb)
        return pooled

    def _normalize_vector(self, vector: List[float]) -> List[float]:
        norm = math.sqrt(sum(x * x for x in vector))
        if norm == 0:
            return vector
        return [x / norm for x in vector]

    async def _generate_embeddings_local(self, texts: List[str]) -> List[List[float]]:
        try:
            import torch
            import torch.nn.functional as F
            from transformers import AutoTokenizer, AutoModel
        except ImportError as e:
            raise EmbeddingException(
                f"Failed to run Hugging Face model locally: torch or transformers is not installed. {str(e)}"
            )

        # Lazy load local model and tokenizer to save startup memory
        if self._local_model is None:
            logger.info(f"Loading Hugging Face model locally: {self.model_name}...")
            try:
                # Load synchronously in executor to prevent event loop blocking
                self._local_tokenizer = await asyncio.to_thread(AutoTokenizer.from_pretrained, self.model_name)
                self._local_model = await asyncio.to_thread(AutoModel.from_pretrained, self.model_name)
                self._local_model.eval()
                logger.info("Local Hugging Face model loaded successfully.")
            except Exception as e:
                raise EmbeddingException(f"Failed to load local Hugging Face model {self.model_name}: {str(e)}")

        processed_texts = []
        is_bge = "bge" in self.model_name.lower()
        for text in texts:
            if is_bge and len(texts) == 1 and not text.startswith("Represent this sentence"):
                processed_texts.append(f"Represent this sentence for searching relevant passages: {text}")
            else:
                processed_texts.append(text)

        try:
            logger.info(f"Tokenizing and encoding {len(processed_texts)} texts locally...")
            
            def _inference():
                encoded_input = self._local_tokenizer(
                    processed_texts,
                    padding=True,
                    truncation=True,
                    return_tensors='pt'
                )
                with torch.no_grad():
                    model_output = self._local_model(**encoded_input)
                    
                    if is_bge:
                        # BGE uses CLS token pooling
                        embeddings = model_output[0][:, 0]
                    else:
                        # Mean pooling
                        token_embeddings = model_output[0]
                        attention_mask = encoded_input['attention_mask']
                        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
                        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
                        sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
                        embeddings = sum_embeddings / sum_mask
                        
                    # Normalize embeddings
                    normalized = F.normalize(embeddings, p=2, dim=1)
                    return normalized.tolist()

            embeddings_list = await asyncio.to_thread(_inference)
            return embeddings_list
            
        except Exception as e:
            logger.error(f"Local Hugging Face embedding generation failed: {str(e)}")
            raise EmbeddingException(f"Failed to generate embeddings locally: {str(e)}")
